In [1]:
import pyspark
from pyspark.sql import SparkSession

In [2]:
spark = SparkSession.builder \
    .master("local[*]") \
    .appName('test') \
    .getOrCreate()

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
25/08/15 07:08:20 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [3]:
df_green = spark.read \
    .option("header", "true") \
    .csv('data/raw/green/2021/01/')

In [4]:
df_green.show()

+--------+--------------------+---------------------+------------------+----------+------------+------------+---------------+-------------+-----------+-----+-------+----------+------------+---------+---------------------+------------+------------+---------+--------------------+
|VendorID|lpep_pickup_datetime|lpep_dropoff_datetime|store_and_fwd_flag|RatecodeID|PULocationID|DOLocationID|passenger_count|trip_distance|fare_amount|extra|mta_tax|tip_amount|tolls_amount|ehail_fee|improvement_surcharge|total_amount|payment_type|trip_type|congestion_surcharge|
+--------+--------------------+---------------------+------------------+----------+------------+------------+---------------+-------------+-----------+-----+-------+----------+------------+---------+---------------------+------------+------------+---------+--------------------+
|       2| 2021-01-01 00:15:56|  2021-01-01 00:19:52|                 N|         1|          43|         151|              1|         1.01|        5.5|  0.5|    0.5|         0|           0|     NULL|                  0.3|         6.8|           2|        1|                   0|
|       2| 2021-01-01 00:25:59|  2021-01-01 00:34:44|                 N|         1|         166|         239|              1|         2.53|         10|  0.5|    0.5|      2.81|           0|     NULL|                  0.3|       16.86|           1|        1|                2.75|
|       2| 2021-01-01 00:45:57|  2021-01-01 00:51:55|                 N|         1|          41|          42|              1|         1.12|          6|  0.5|    0.5|         1|           0|     NULL|                  0.3|         8.3|           1|        1|                   0|
|       2| 2020-12-31 23:57:51|  2021-01-01 00:04:56|                 N|         1|         168|          75|              1|         1.99|          8|  0.5|    0.5|         0|           0|     NULL|                  0.3|         9.3|           2|        1|                   0|
|       2| 2021-01-01 00:16:36|  2021-01-01 00:16:40|                 N|         2|         265|         265|              3|          .00|        -52|    0|   -0.5|         0|           0|     NULL|                 -0.3|       -52.8|           3|        1|                   0|
|       2| 2021-01-01 00:16:36|  2021-01-01 00:16:40|                 N|         2|         265|         265|              3|          .00|         52|    0|    0.5|         0|           0|     NULL|                  0.3|        52.8|           2|        1|                   0|
|       2| 2021-01-01 00:19:14|  2021-01-01 00:19:21|                 N|         5|         265|         265|              1|          .00|        180|    0|      0|     36.06|           0|     NULL|                  0.3|      216.36|           1|        2|                   0|
|       2| 2021-01-01 00:26:31|  2021-01-01 00:28:50|                 N|         1|          75|          75|              6|          .45|        3.5|  0.5|    0.5|      0.96|           0|     NULL|                  0.3|        5.76|           1|        1|                   0|
|       2| 2021-01-01 00:57:46|  2021-01-01 00:57:57|                 N|         1|         225|         225|              1|          .00|        2.5|  0.5|    0.5|         0|           0|     NULL|                  0.3|         3.8|           2|        1|                   0|
|       2| 2021-01-01 00:58:32|  2021-01-01 01:32:34|                 N|         1|         225|         265|              1|        12.19|         38|  0.5|    0.5|      2.75|           0|     NULL|                  0.3|       42.05|           1|        1|                   0|
|       2| 2021-01-01 00:31:14|  2021-01-01 00:55:07|                 N|         1|         244|         244|              2|         3.39|         18|  0.5|    0.5|         0|           0|     NULL|                  0.3|        19.3|           2|        1|                   0|
|       2| 2021-01-01 00:08:50|  2021-01-01 00:21:56|                 N|         1|          75|         213|              1|         6.69|       19.5|  0.5|    0.5|         0|           0|     NULL|                  0.3|        20.8|           2|        1|                   0|
|       2| 2021-01-01 00:35:13|  2021-01-01 00:44:44|                 N|         1|          74|         238|              1|         2.34|         10|  0.5|    0.5|         0|           0|     NULL|                  0.3|       14.05|           1|        1|                2.75|
|       2| 2021-01-01 00:39:57|  2021-01-01 00:55:25|                 N|         1|          74|          60|              1|         5.48|         18|  0.5|    0.5|         0|           0|     NULL|                  0.3|        19.3|           2|        1|                   0|
|       1| 2021-01-01 00:51:27|  2021-01-01 00:57:20|                 N|         1|          42|          41|              2|          .90|          6|  0.5|    0.5|         0|           0|     NULL|                  0.3|         7.3|           1|        1|                   0|
|       2| 2021-01-01 00:29:05|  2021-01-01 00:29:07|                 N|         5|          42|         264|              1|          .00|         10|    0|      0|      2.06|           0|     NULL|                  0.3|       12.36|           1|        2|                   0|
|       2| 2021-01-01 00:32:07|  2021-01-01 00:42:54|                 N|         1|          74|         116|              1|         2.08|        9.5|  0.5|    0.5|      2.16|           0|     NULL|                  0.3|       12.96|           1|        1|                   0|
|       2| 2021-01-01 00:49:59|  2021-01-01 01:05:01|                 N|         1|         116|         143|              1|         4.64|       16.5|  0.5|    0.5|      5.14|           0|     NULL|                  0.3|       25.69|           1|        1|                2.75|
|       2| 2021-01-01 00:07:20|  2021-01-01 00:12:01|                 N|         1|          75|          42|              1|         1.68|        6.5|  0.5|    0.5|         0|           0|     NULL|                  0.3|         7.8|           2|        1|                   0|
|       2| 2021-01-01 00:25:54|  2021-01-01 00:28:20|                 N|         1|          74|          75|              1|          .68|          4|  0.5|    0.5|         0|           0|     NULL|                  0.3|         5.3|           2|        1|                   0|
+--------+--------------------+---------------------+------------------+----------+------------+------------+---------------+-------------+-----------+-----+-------+----------+------------+---------+---------------------+------------+------------+---------+--------------------+
only showing top 20 rows

In [5]:
df_green.printSchema()

root
 |-- VendorID: string (nullable = true)
 |-- lpep_pickup_datetime: string (nullable = true)
 |-- lpep_dropoff_datetime: string (nullable = true)
 |-- store_and_fwd_flag: string (nullable = true)
 |-- RatecodeID: string (nullable = true)
 |-- PULocationID: string (nullable = true)
 |-- DOLocationID: string (nullable = true)
 |-- passenger_count: string (nullable = true)
 |-- trip_distance: string (nullable = true)
 |-- fare_amount: string (nullable = true)
 |-- extra: string (nullable = true)
 |-- mta_tax: string (nullable = true)
 |-- tip_amount: string (nullable = true)
 |-- tolls_amount: string (nullable = true)
 |-- ehail_fee: string (nullable = true)
 |-- improvement_surcharge: string (nullable = true)
 |-- total_amount: string (nullable = true)
 |-- payment_type: string (nullable = true)
 |-- trip_type: string (nullable = true)
 |-- congestion_surcharge: string (nullable = true)

In [6]:
import pandas as pd

In [7]:
df_green_pd = pd.read_csv('data/raw/green/2021/01/green_tripdata_2021_01.csv.gz', nrows=1000)

In [8]:
df_green_pd

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2021-01-01 00:15:56,2021-01-01 00:19:52,N,1,43,151,1,1.01,5.5,0.5,0.5,0.00,0.00,NaN,0.3,6.80,2,1,0.00
1,2,2021-01-01 00:25:59,2021-01-01 00:34:44,N,1,166,239,1,2.53,10.0,0.5,0.5,2.81,0.00,NaN,0.3,16.86,1,1,2.75
2,2,2021-01-01 00:45:57,2021-01-01 00:51:55,N,1,41,42,1,1.12,6.0,0.5,0.5,1.00,0.00,NaN,0.3,8.30,1,1,0.00
3,2,2020-12-31 23:57:51,2021-01-01 00:04:56,N,1,168,75,1,1.99,8.0,0.5,0.5,0.00,0.00,NaN,0.3,9.30,2,1,0.00
4,2,2021-01-01 00:16:36,2021-01-01 00:16:40,N,2,265,265,3,0.00,-52.0,0.0,-0.5,0.00,0.00,NaN,-0.3,-52.80,3,1,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2,2021-01-02 12:48:43,2021-01-02 13:54:15,N,1,15,177,1,25.76,77.0,0.0,0.5,2.75,12.24,NaN,0.3,92.79,1,1,0.00
996,1,2021-01-02 12:16:47,2021-01-02 12:24:56,N,1,116,74,1,2.00,9.0,0.0,0.5,1.95,0.00,NaN,0.3,11.75,1,1,0.00
997,2,2021-01-02 12:07:17,2021-01-02 12:12:06,N,1,42,41,1,0.87,5.5,0.0,0.5,0.00,0.00,NaN,0.3,6.30,2,1,0.00
998,2,2021-01-02 12:32:45,2021-01-02 12:59:46,N,1,82,218,1,11.88,35.0,0.0,0.5,0.00,0.00,NaN,0.3,35.80,2,1,0.00
999,2,2021-01-02 12:02:46,2021-01-02 12:09:02,N,1,166,116,1,0.90,6.0,0.0,0.5,0.00,0.00,NaN,0.3,6.80,2,1,0.00

In [9]:
df_green_pd.dtypes

VendorID                   int64
lpep_pickup_datetime      object
lpep_dropoff_datetime     object
store_and_fwd_flag        object
RatecodeID                 int64
PULocationID               int64
DOLocationID               int64
passenger_count            int64
trip_distance            float64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
ehail_fee                float64
improvement_surcharge    float64
total_amount             float64
payment_type               int64
trip_type                  int64
congestion_surcharge     float64
dtype: object

In [10]:
spark.createDataFrame(df_green_pd).schema

StructType([StructField('VendorID', LongType(), True), StructField('lpep_pickup_datetime', StringType(), True), StructField('lpep_dropoff_datetime', StringType(), True), StructField('store_and_fwd_flag', StringType(), True), StructField('RatecodeID', LongType(), True), StructField('PULocationID', LongType(), True), StructField('DOLocationID', LongType(), True), StructField('passenger_count', LongType(), True), StructField('trip_distance', DoubleType(), True), StructField('fare_amount', DoubleType(), True), StructField('extra', DoubleType(), True), StructField('mta_tax', DoubleType(), True), StructField('tip_amount', DoubleType(), True), StructField('tolls_amount', DoubleType(), True), StructField('ehail_fee', DoubleType(), True), StructField('improvement_surcharge', DoubleType(), True), StructField('total_amount', DoubleType(), True), StructField('payment_type', LongType(), True), StructField('trip_type', LongType(), True), StructField('congestion_surcharge', DoubleType(), True)])

In [11]:
from pyspark.sql import types

In [12]:
green_schema = types.StructType([
    types.StructField('VendorID', types.IntegerType(), True),
    types.StructField('lpep_pickup_datetime', types.TimestampType(), True),
    types.StructField('lpep_dropoff_datetime', types.TimestampType(), True),
    types.StructField('store_and_fwd_flag', types.StringType(), True),
    types.StructField('RatecodeID', types.IntegerType(), True),
    types.StructField('PULocationID', types.IntegerType(), True),
    types.StructField('DOLocationID', types.IntegerType(), True),
    types.StructField('passenger_count', types.IntegerType(), True),
    types.StructField('trip_distance', types.DoubleType(), True),
    types.StructField('fare_amount', types.DoubleType(), True),
    types.StructField('extra', types.DoubleType(), True),
    types.StructField('mta_tax', types.DoubleType(), True),
    types.StructField('tip_amount', types.DoubleType(), True),
    types.StructField('tolls_amount', types.DoubleType(), True),
    types.StructField('ehail_fee', types.DoubleType(), True),
    types.StructField('improvement_surcharge', types.DoubleType(), True),
    types.StructField('total_amount', types.DoubleType(), True),
    types.StructField('payment_type', types.IntegerType(), True),
    types.StructField('trip_type', types.IntegerType(), True),
    types.StructField('congestion_surcharge', types.DoubleType(), True)
 ])

In [13]:
df_green = spark.read \
    .option("header", "true") \
    .schema(green_schema) \
    .csv('data/raw/green/2021/01/')

In [14]:
df_green.printSchema()

root
 |-- VendorID: integer (nullable = true)
 |-- lpep_pickup_datetime: timestamp (nullable = true)
 |-- lpep_dropoff_datetime: timestamp (nullable = true)
 |-- store_and_fwd_flag: string (nullable = true)
 |-- RatecodeID: integer (nullable = true)
 |-- PULocationID: integer (nullable = true)
 |-- DOLocationID: integer (nullable = true)
 |-- passenger_count: integer (nullable = true)
 |-- trip_distance: double (nullable = true)
 |-- fare_amount: double (nullable = true)
 |-- extra: double (nullable = true)
 |-- mta_tax: double (nullable = true)
 |-- tip_amount: double (nullable = true)
 |-- tolls_amount: double (nullable = true)
 |-- ehail_fee: double (nullable = true)
 |-- improvement_surcharge: double (nullable = true)
 |-- total_amount: double (nullable = true)
 |-- payment_type: integer (nullable = true)
 |-- trip_type: integer (nullable = true)
 |-- congestion_surcharge: double (nullable = true)

In [15]:
df_yellow_pd = pd.read_csv('data/raw/yellow/2021/01/yellow_tripdata_2021_01.csv.gz', nrows=1000)

In [16]:
df_yellow_pd

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1,2021-01-01 00:57:42,2021-01-01 01:08:18,1,3.10,1,N,264,264,1,11.5,0.5,0.5,1.00,0.0,0.3,13.80,0.0
996,2,2021-01-01 00:19:34,2021-01-01 00:31:34,1,2.77,1,N,170,239,1,11.0,0.5,0.5,2.96,0.0,0.3,17.76,2.5
997,2,2021-01-01 00:16:38,2021-01-01 00:24:23,3,2.01,1,N,41,263,1,8.5,0.5,0.5,2.46,0.0,0.3,14.76,2.5
998,2,2021-01-01 00:28:09,2021-01-01 00:40:08,1,3.35,1,N,263,186,4,-12.0,-0.5,-0.5,0.00,0.0,-0.3,-15.80,-2.5
999,2,2021-01-01 00:28:09,2021-01-01 00:40:08,1,3.35,1,N,263,186,2,12.0,0.5,0.5,0.00,0.0,0.3,15.80,2.5

In [17]:
spark.createDataFrame(df_yellow_pd).schema

StructType([StructField('VendorID', LongType(), True), StructField('tpep_pickup_datetime', StringType(), True), StructField('tpep_dropoff_datetime', StringType(), True), StructField('passenger_count', LongType(), True), StructField('trip_distance', DoubleType(), True), StructField('RatecodeID', LongType(), True), StructField('store_and_fwd_flag', StringType(), True), StructField('PULocationID', LongType(), True), StructField('DOLocationID', LongType(), True), StructField('payment_type', LongType(), True), StructField('fare_amount', DoubleType(), True), StructField('extra', DoubleType(), True), StructField('mta_tax', DoubleType(), True), StructField('tip_amount', DoubleType(), True), StructField('tolls_amount', DoubleType(), True), StructField('improvement_surcharge', DoubleType(), True), StructField('total_amount', DoubleType(), True), StructField('congestion_surcharge', DoubleType(), True)])

In [18]:
yellow_schema = types.StructType([
    types.StructField('VendorID', types.IntegerType(), True), 
    types.StructField('tpep_pickup_datetime', types.TimestampType(), True), 
    types.StructField('tpep_dropoff_datetime', types.TimestampType(), True), 
    types.StructField('passenger_count', types.IntegerType(), True), 
    types.StructField('trip_distance', types.DoubleType(), True), 
    types.StructField('RatecodeID', types.IntegerType(), True), 
    types.StructField('store_and_fwd_flag', types.StringType(), True), 
    types.StructField('PULocationID', types.IntegerType(), True), 
    types.StructField('DOLocationID', types.IntegerType(), True), 
    types.StructField('payment_type', types.IntegerType(), True), 
    types.StructField('fare_amount', types.DoubleType(), True), 
    types.StructField('extra', types.DoubleType(), True), 
    types.StructField('mta_tax', types.DoubleType(), True), 
    types.StructField('tip_amount', types.DoubleType(), True), 
    types.StructField('tolls_amount', types.DoubleType(), True), 
    types.StructField('improvement_surcharge', types.DoubleType(), True), 
    types.StructField('total_amount', types.DoubleType(), True), 
    types.StructField('congestion_surcharge', types.DoubleType(), True)
])

In [19]:
df_yellow = spark.read \
    .option("header", "true") \
    .schema(yellow_schema) \
    .csv('data/raw/yellow/2021/01/')

In [20]:
df_yellow.dtypes

[('VendorID', 'int'),
 ('tpep_pickup_datetime', 'timestamp'),
 ('tpep_dropoff_datetime', 'timestamp'),
 ('passenger_count', 'int'),
 ('trip_distance', 'double'),
 ('RatecodeID', 'int'),
 ('store_and_fwd_flag', 'string'),
 ('PULocationID', 'int'),
 ('DOLocationID', 'int'),
 ('payment_type', 'int'),
 ('fare_amount', 'double'),
 ('extra', 'double'),
 ('mta_tax', 'double'),
 ('tip_amount', 'double'),
 ('tolls_amount', 'double'),
 ('improvement_surcharge', 'double'),
 ('total_amount', 'double'),
 ('congestion_surcharge', 'double')]

In [22]:
df_green \
    .repartition(4) \
    .write.parquet('data/pq/green/2021/01/')

In [24]:
year = 2021

for month in range(1, 13):
    print(f'processing data for {year}/{month}')
    
    input_path = f'data/raw/green/{year}/{month:02d}/'
    output_path = f'data/pq/green/{year}/{month:02d}/'
    
    df_green = spark.read \
        .option("header", "true") \
        .schema(green_schema) \
        .csv(input_path)
    
    df_green \
        .repartition(4) \
        .write.parquet(output_path, mode="overwrite")

processing data for 2021/1

processing data for 2021/2

processing data for 2021/3

processing data for 2021/4

processing data for 2021/5

processing data for 2021/6

processing data for 2021/7

processing data for 2021/8
processing data for 2021/9

AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/home/sweantu/code/airbnb/spark_practice/data/raw/green/2021/09.

In [25]:
year = 2021

for month in range(1, 13):
    print(f'processing data for {year}/{month}')
    
    input_path = f'data/raw/yellow/{year}/{month:02d}/'
    output_path = f'data/pq/yellow/{year}/{month:02d}/'
    
    df_yellow = spark.read \
        .option("header", "true") \
        .schema(yellow_schema) \
        .csv(input_path)
    
    df_yellow \
        .repartition(4) \
        .write.parquet(output_path)

processing data for 2021/1

processing data for 2021/2

processing data for 2021/3

processing data for 2021/4

processing data for 2021/5

processing data for 2021/6

processing data for 2021/7

processing data for 2021/8
processing data for 2021/9

AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/home/sweantu/code/airbnb/spark_practice/data/raw/yellow/2021/09.

In [26]:
!ls -lhR data

data:
total 8.0K
drwxr-xr-x 4 sweantu sweantu 4.0K Aug 15 07:20 pq
drwxrwxr-x 4 sweantu sweantu 4.0K Aug 15 07:10 raw

data/pq:
total 8.0K
drwxr-xr-x 3 sweantu sweantu 4.0K Aug 15 07:18 green
drwxr-xr-x 3 sweantu sweantu 4.0K Aug 15 07:20 yellow

data/pq/green:
total 4.0K
drwxr-xr-x 10 sweantu sweantu 4.0K Aug 15 07:19 2021

data/pq/green/2021:
total 32K
drwxr-xr-x 2 sweantu sweantu 4.0K Aug 15 07:19 01
drwxr-xr-x 2 sweantu sweantu 4.0K Aug 15 07:19 02
drwxr-xr-x 2 sweantu sweantu 4.0K Aug 15 07:19 03
drwxr-xr-x 2 sweantu sweantu 4.0K Aug 15 07:19 04
drwxr-xr-x 2 sweantu sweantu 4.0K Aug 15 07:19 05
drwxr-xr-x 2 sweantu sweantu 4.0K Aug 15 07:19 06
drwxr-xr-x 2 sweantu sweantu 4.0K Aug 15 07:19 07
drwxr-xr-x 2 sweantu sweantu 4.0K Aug 15 07:19 08

data/pq/green/2021/01:
total 2.2M
-rw-r--r-- 1 sweantu sweantu    0 Aug 15 07:19 _SUCCESS
-rw-r--r-- 1 sweantu sweantu 545K Aug 15 07:19 part-00000-9d4f8567-44e6-4b0c-81bc-c361985e4260-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 545K Aug 15 07:19 part-00001-9d4f8567-44e6-4b0c-81bc-c361985e4260-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 548K Aug 15 07:19 part-00002-9d4f8567-44e6-4b0c-81bc-c361985e4260-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 546K Aug 15 07:19 part-00003-9d4f8567-44e6-4b0c-81bc-c361985e4260-c000.snappy.parquet

data/pq/green/2021/02:
total 1.9M
-rw-r--r-- 1 sweantu sweantu    0 Aug 15 07:19 _SUCCESS
-rw-r--r-- 1 sweantu sweantu 462K Aug 15 07:19 part-00000-20044390-1a4f-4a20-872e-86287fb7192b-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 462K Aug 15 07:19 part-00001-20044390-1a4f-4a20-872e-86287fb7192b-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 460K Aug 15 07:19 part-00002-20044390-1a4f-4a20-872e-86287fb7192b-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 461K Aug 15 07:19 part-00003-20044390-1a4f-4a20-872e-86287fb7192b-c000.snappy.parquet

data/pq/green/2021/03:
total 2.4M
-rw-r--r-- 1 sweantu sweantu    0 Aug 15 07:19 _SUCCESS
-rw-r--r-- 1 sweantu sweantu 591K Aug 15 07:19 part-00000-17c6db03-14cb-4ce7-be5e-3b2797e9a8b1-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 594K Aug 15 07:19 part-00001-17c6db03-14cb-4ce7-be5e-3b2797e9a8b1-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 595K Aug 15 07:19 part-00002-17c6db03-14cb-4ce7-be5e-3b2797e9a8b1-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 594K Aug 15 07:19 part-00003-17c6db03-14cb-4ce7-be5e-3b2797e9a8b1-c000.snappy.parquet

data/pq/green/2021/04:
total 2.5M
-rw-r--r-- 1 sweantu sweantu    0 Aug 15 07:19 _SUCCESS
-rw-r--r-- 1 sweantu sweantu 619K Aug 15 07:19 part-00000-f9797cff-78db-4776-bff8-6cc5e90111db-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 618K Aug 15 07:19 part-00001-f9797cff-78db-4776-bff8-6cc5e90111db-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 620K Aug 15 07:19 part-00002-f9797cff-78db-4776-bff8-6cc5e90111db-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 618K Aug 15 07:19 part-00003-f9797cff-78db-4776-bff8-6cc5e90111db-c000.snappy.parquet

data/pq/green/2021/05:
total 2.5M
-rw-r--r-- 1 sweantu sweantu    0 Aug 15 07:19 _SUCCESS
-rw-r--r-- 1 sweantu sweantu 640K Aug 15 07:19 part-00000-85cf3c97-0b89-45f4-8e09-3d9151565668-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 638K Aug 15 07:19 part-00001-85cf3c97-0b89-45f4-8e09-3d9151565668-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 636K Aug 15 07:19 part-00002-85cf3c97-0b89-45f4-8e09-3d9151565668-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 640K Aug 15 07:19 part-00003-85cf3c97-0b89-45f4-8e09-3d9151565668-c000.snappy.parquet

data/pq/green/2021/06:
total 2.6M
-rw-r--r-- 1 sweantu sweantu    0 Aug 15 07:19 _SUCCESS
-rw-r--r-- 1 sweantu sweantu 641K Aug 15 07:19 part-00000-8455df08-73b2-4843-8439-c5d945171c26-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 643K Aug 15 07:19 part-00001-8455df08-73b2-4843-8439-c5d945171c26-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 643K Aug 15 07:19 part-00002-8455df08-73b2-4843-8439-c5d945171c26-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 642K Aug 15 07:19 part-00003-8455df08-73b2-4843-8439-c5d945171c26-c000.snappy.parquet

data/pq/green/2021/07:
total 2.5M
-rw-r--r-- 1 sweantu sweantu    0 Aug 15 07:19 _SUCCESS
-rw-r--r-- 1 sweantu sweantu 624K Aug 15 07:19 part-00000-2b1bed05-12e7-4b2b-bbd8-30ec89f5e3b3-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 621K Aug 15 07:19 part-00001-2b1bed05-12e7-4b2b-bbd8-30ec89f5e3b3-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 622K Aug 15 07:19 part-00002-2b1bed05-12e7-4b2b-bbd8-30ec89f5e3b3-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 621K Aug 15 07:19 part-00003-2b1bed05-12e7-4b2b-bbd8-30ec89f5e3b3-c000.snappy.parquet

data/pq/green/2021/08:
total 4.0K
-rw-r--r-- 1 sweantu sweantu    0 Aug 15 07:19 _SUCCESS
-rw-r--r-- 1 sweantu sweantu 2.1K Aug 15 07:19 part-00000-e5f67910-386b-4781-89f9-d5ed14b9307b-c000.snappy.parquet

data/pq/yellow:
total 4.0K
drwxr-xr-x 10 sweantu sweantu 4.0K Aug 15 07:23 2021

data/pq/yellow/2021:
total 32K
drwxr-xr-x 2 sweantu sweantu 4.0K Aug 15 07:20 01
drwxr-xr-x 2 sweantu sweantu 4.0K Aug 15 07:20 02
drwxr-xr-x 2 sweantu sweantu 4.0K Aug 15 07:20 03
drwxr-xr-x 2 sweantu sweantu 4.0K Aug 15 07:21 04
drwxr-xr-x 2 sweantu sweantu 4.0K Aug 15 07:21 05
drwxr-xr-x 2 sweantu sweantu 4.0K Aug 15 07:22 06
drwxr-xr-x 2 sweantu sweantu 4.0K Aug 15 07:23 07
drwxr-xr-x 2 sweantu sweantu 4.0K Aug 15 07:23 08

data/pq/yellow/2021/01:
total 36M
-rw-r--r-- 1 sweantu sweantu    0 Aug 15 07:20 _SUCCESS
-rw-r--r-- 1 sweantu sweantu 9.0M Aug 15 07:20 part-00000-ab11260f-f2c1-4f6c-a62c-5298c54b6b6a-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 9.0M Aug 15 07:20 part-00001-ab11260f-f2c1-4f6c-a62c-5298c54b6b6a-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 9.0M Aug 15 07:20 part-00002-ab11260f-f2c1-4f6c-a62c-5298c54b6b6a-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 9.0M Aug 15 07:20 part-00003-ab11260f-f2c1-4f6c-a62c-5298c54b6b6a-c000.snappy.parquet

data/pq/yellow/2021/02:
total 36M
-rw-r--r-- 1 sweantu sweantu    0 Aug 15 07:20 _SUCCESS
-rw-r--r-- 1 sweantu sweantu 9.0M Aug 15 07:20 part-00000-b5fc66b6-fc73-4bc3-bd97-1526aff36bfd-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 9.0M Aug 15 07:20 part-00001-b5fc66b6-fc73-4bc3-bd97-1526aff36bfd-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 9.0M Aug 15 07:20 part-00002-b5fc66b6-fc73-4bc3-bd97-1526aff36bfd-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 9.0M Aug 15 07:20 part-00003-b5fc66b6-fc73-4bc3-bd97-1526aff36bfd-c000.snappy.parquet

data/pq/yellow/2021/03:
total 50M
-rw-r--r-- 1 sweantu sweantu   0 Aug 15 07:20 _SUCCESS
-rw-r--r-- 1 sweantu sweantu 13M Aug 15 07:20 part-00000-e0ffec7d-7e99-4734-99a8-dc15f29b67ef-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 13M Aug 15 07:20 part-00001-e0ffec7d-7e99-4734-99a8-dc15f29b67ef-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 13M Aug 15 07:20 part-00002-e0ffec7d-7e99-4734-99a8-dc15f29b67ef-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 13M Aug 15 07:20 part-00003-e0ffec7d-7e99-4734-99a8-dc15f29b67ef-c000.snappy.parquet

data/pq/yellow/2021/04:
total 57M
-rw-r--r-- 1 sweantu sweantu   0 Aug 15 07:21 _SUCCESS
-rw-r--r-- 1 sweantu sweantu 15M Aug 15 07:21 part-00000-ab76d548-6470-4279-8006-976519d97452-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 15M Aug 15 07:21 part-00001-ab76d548-6470-4279-8006-976519d97452-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 15M Aug 15 07:21 part-00002-ab76d548-6470-4279-8006-976519d97452-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 15M Aug 15 07:21 part-00003-ab76d548-6470-4279-8006-976519d97452-c000.snappy.parquet

data/pq/yellow/2021/05:
total 65M
-rw-r--r-- 1 sweantu sweantu   0 Aug 15 07:21 _SUCCESS
-rw-r--r-- 1 sweantu sweantu 17M Aug 15 07:21 part-00000-becf9f73-4b79-4d7f-a44c-4500b3f59d7e-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 17M Aug 15 07:21 part-00001-becf9f73-4b79-4d7f-a44c-4500b3f59d7e-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 17M Aug 15 07:21 part-00002-becf9f73-4b79-4d7f-a44c-4500b3f59d7e-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 17M Aug 15 07:21 part-00003-becf9f73-4b79-4d7f-a44c-4500b3f59d7e-c000.snappy.parquet

data/pq/yellow/2021/06:
total 74M
-rw-r--r-- 1 sweantu sweantu   0 Aug 15 07:22 _SUCCESS
-rw-r--r-- 1 sweantu sweantu 19M Aug 15 07:22 part-00000-5fe3cd00-be33-40f0-a40a-9f2405edd39a-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 19M Aug 15 07:22 part-00001-5fe3cd00-be33-40f0-a40a-9f2405edd39a-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 19M Aug 15 07:22 part-00002-5fe3cd00-be33-40f0-a40a-9f2405edd39a-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 19M Aug 15 07:22 part-00003-5fe3cd00-be33-40f0-a40a-9f2405edd39a-c000.snappy.parquet

data/pq/yellow/2021/07:
total 74M
-rw-r--r-- 1 sweantu sweantu   0 Aug 15 07:23 _SUCCESS
-rw-r--r-- 1 sweantu sweantu 19M Aug 15 07:22 part-00000-61a8eca4-a7c1-49ee-aa01-f82b1b898f2c-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 19M Aug 15 07:22 part-00001-61a8eca4-a7c1-49ee-aa01-f82b1b898f2c-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 19M Aug 15 07:23 part-00002-61a8eca4-a7c1-49ee-aa01-f82b1b898f2c-c000.snappy.parquet
-rw-r--r-- 1 sweantu sweantu 19M Aug 15 07:23 part-00003-61a8eca4-a7c1-49ee-aa01-f82b1b898f2c-c000.snappy.parquet

data/pq/yellow/2021/08:
total 4.0K
-rw-r--r-- 1 sweantu sweantu    0 Aug 15 07:23 _SUCCESS
-rw-r--r-- 1 sweantu sweantu 2.0K Aug 15 07:23 part-00000-c1ed88b9-9d36-4da2-9a41-a8e279f8ee32-c000.snappy.parquet

data/raw:
total 8.0K
drwxrwxr-x 3 sweantu sweantu 4.0K Aug 15 07:10 green
drwxrwxr-x 3 sweantu sweantu 4.0K Aug 15 07:10 yellow

data/raw/green:
total 4.0K
drwxrwxr-x 10 sweantu sweantu 4.0K Aug 15 07:11 2021

data/raw/green/2021:
total 32K
drwxrwxr-x 2 sweantu sweantu 4.0K Aug 15 07:10 01
drwxrwxr-x 2 sweantu sweantu 4.0K Aug 15 07:11 02
drwxrwxr-x 2 sweantu sweantu 4.0K Aug 15 07:11 03
drwxrwxr-x 2 sweantu sweantu 4.0K Aug 15 07:11 04
drwxrwxr-x 2 sweantu sweantu 4.0K Aug 15 07:11 05
drwxrwxr-x 2 sweantu sweantu 4.0K Aug 15 07:11 06
drwxrwxr-x 2 sweantu sweantu 4.0K Aug 15 07:11 07
drwxrwxr-x 2 sweantu sweantu 4.0K Aug 15 07:11 08

data/raw/green/2021/01:
total 1.4M
-rw-rw-r-- 1 sweantu sweantu 1.4M Jul 14  2022 green_tripdata_2021_01.csv.gz

data/raw/green/2021/02:
total 1.2M
-rw-rw-r-- 1 sweantu sweantu 1.2M Jul 14  2022 green_tripdata_2021_02.csv.gz

data/raw/green/2021/03:
total 1.5M
-rw-rw-r-- 1 sweantu sweantu 1.5M Jul 14  2022 green_tripdata_2021_03.csv.gz

data/raw/green/2021/04:
total 1.6M
-rw-rw-r-- 1 sweantu sweantu 1.6M Jul 14  2022 green_tripdata_2021_04.csv.gz

data/raw/green/2021/05:
total 1.6M
-rw-rw-r-- 1 sweantu sweantu 1.6M Jul 14  2022 green_tripdata_2021_05.csv.gz

data/raw/green/2021/06:
total 1.6M
-rw-rw-r-- 1 sweantu sweantu 1.6M Jul 14  2022 green_tripdata_2021_06.csv.gz

data/raw/green/2021/07:
total 1.5M
-rw-rw-r-- 1 sweantu sweantu 1.5M Jul 14  2022 green_tripdata_2021_07.csv.gz

data/raw/green/2021/08:
total 0
-rw-rw-r-- 1 sweantu sweantu 0 Aug 15 07:11 green_tripdata_2021_08.csv.gz

data/raw/yellow:
total 4.0K
drwxrwxr-x 10 sweantu sweantu 4.0K Aug 15 07:10 2021

data/raw/yellow/2021:
total 32K
drwxrwxr-x 2 sweantu sweantu 4.0K Aug 15 07:10 01
drwxrwxr-x 2 sweantu sweantu 4.0K Aug 15 07:10 02
drwxrwxr-x 2 sweantu sweantu 4.0K Aug 15 07:10 03
drwxrwxr-x 2 sweantu sweantu 4.0K Aug 15 07:10 04
drwxrwxr-x 2 sweantu sweantu 4.0K Aug 15 07:10 05
drwxrwxr-x 2 sweantu sweantu 4.0K Aug 15 07:10 06
drwxrwxr-x 2 sweantu sweantu 4.0K Aug 15 07:10 07
drwxrwxr-x 2 sweantu sweantu 4.0K Aug 15 07:10 08

data/raw/yellow/2021/01:
total 24M
-rw-rw-r-- 1 sweantu sweantu 24M Jul 14  2022 yellow_tripdata_2021_01.csv.gz

data/raw/yellow/2021/02:
total 24M
-rw-rw-r-- 1 sweantu sweantu 24M Jul 14  2022 yellow_tripdata_2021_02.csv.gz

data/raw/yellow/2021/03:
total 34M
-rw-rw-r-- 1 sweantu sweantu 34M Jul 14  2022 yellow_tripdata_2021_03.csv.gz

data/raw/yellow/2021/04:
total 39M
-rw-rw-r-- 1 sweantu sweantu 39M Jul 14  2022 yellow_tripdata_2021_04.csv.gz

data/raw/yellow/2021/05:
total 45M
-rw-rw-r-- 1 sweantu sweantu 45M Jul 14  2022 yellow_tripdata_2021_05.csv.gz

data/raw/yellow/2021/06:
total 51M
-rw-rw-r-- 1 sweantu sweantu 51M Jul 14  2022 yellow_tripdata_2021_06.csv.gz

data/raw/yellow/2021/07:
total 50M
-rw-rw-r-- 1 sweantu sweantu 50M Jul 14  2022 yellow_tripdata_2021_07.csv.gz

data/raw/yellow/2021/08:
total 0
-rw-rw-r-- 1 sweantu sweantu 0 Aug 15 07:10 yellow_tripdata_2021_08.csv.gz